name: .NET CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build & Test .NET
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout du code
        uses: actions/checkout@v6
        # 💡 Tip de pro : Sonar a besoin de tout l'historique Git pour assigner la dette technique au bon développeur (git blame).
        # Il faudra décommenter ces lignes pour désactiver le shallow clone.
        with:
          fetch-depth: 0

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: ☕ Setup Java 17 (Requis par SonarScanner)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: 🔍 Installation globale de SonarScanner pour .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: 📦 Restauration des dépendances
        run: dotnet restore

      # C'est ici que la CI pètera si le code est mal formaté
      - name: 🧹 Vérification du formatage
        run: dotnet format --verify-no-changes

      - name: 🚀 Démarrage de l'analyse SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # Note : Le \ permet de sauter des lignes pour que ce soit plus lisible pour toi
        run: >
          dotnet sonarscanner begin 
          /k:"Bastien-DA_Template-Dotnet-Mongo-Api" 
          /o:"${{ secrets.SONAR_ORGANIZATION_KEY }}"  
          /d:sonar.host.url="https://sonarcloud.io" 
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" 
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
          /d:sonar.qualitygate.wait=true

      - name: 🏗️ Compilation (Build)
        run: dotnet build --no-restore --configuration Release
        
        #- name: 🧪 Tests Unitaires et Couverture de code
        # L'argument --collect déclenche "Coverlet" (inclus par défaut dans les projets de test .NET récents)
        # On lui demande de cracher un fichier au format "OpenCover" car c'est celui que SonarCloud lit le mieux pour le C#
        #run: dotnet test --no-build --configuration Release --verbosity normal --collect:"XPlat Code Coverage" --DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: 🏁 Finalisation de l'analyse SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"